### ISSUE TITLE
Bug: "Error in atexit._run_exitfuncs" when running unit tests

### ISSUE THREAD

**Issue by tterb** [manrajgrover/halo#97] opened 2018-10-05 06:46 UTC
## Description

I'm using the package within a download function like so:
```python
def download(url):
  spinner = Halo(text='Downloading', spinner='dots12')
  spinner.start()
  (...)
  spinner.succeed('Download Complete')
  spinner.stop()
```
While, the package works as expected when running the program, when running unit test with pytest the test output is followed by the error message pasted below. 

### System settings

- Operating System: macOS
- Terminal in use: iTerm2
- Python version: 3.5, 3.6, 3.7
- Halo version: 0.0.17
- `pip freeze` output:

### Error
```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/halo/halo.py", line 78, in clean_up
    self.stop()
  File "/usr/local/lib/python3.7/site-packages/halo/halo.py", line 419, in stop
    self.clear()
  File "/usr/local/lib/python3.7/site-packages/halo/halo.py", line 311, in clear
    self._stream.write('\r')
  File "/usr/local/lib/python3.7/site-packages/colorama/ansitowin32.py", line 40, in write
    self.__convertor.write(text)
  File "/usr/local/lib/python3.7/site-packages/colorama/ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "/usr/local/lib/python3.7/site-packages/colorama/ansitowin32.py", line 169, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "/usr/local/lib/python3.7/site-packages/colorama/ansitowin32.py", line 174, in write_plain_text
    self.wrapped.write(text[start:end])
  File "/usr/local/lib/python3.7/site-packages/colorama/ansitowin32.py", line 40, in write
    self.__convertor.write(text)
  File "/usr/local/lib/python3.7/site-packages/colorama/ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "/usr/local/lib/python3.7/site-packages/colorama/ansitowin32.py", line 169, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "/usr/local/lib/python3.7/site-packages/colorama/ansitowin32.py", line 174, in write_plain_text
    self.wrapped.write(text[start:end])
  File "/usr/local/lib/python3.7/site-packages/_pytest/capture.py", line 358, in write
    self.buffer.write(obj)
ValueError: I/O operation on closed file
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/halo/halo.py", line 78, in clean_up
    self.stop()
  File "/usr/local/lib/python3.7/site-packages/halo/halo.py", line 419, in stop
    self.clear()
  File "/usr/local/lib/python3.7/site-packages/halo/halo.py", line 311, in clear
    self._stream.write('\r')
  File "/usr/local/lib/python3.7/site-packages/colorama/ansitowin32.py", line 40, in write
    self.__convertor.write(text)
  File "/usr/local/lib/python3.7/site-packages/colorama/ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "/usr/local/lib/python3.7/site-packages/colorama/ansitowin32.py", line 169, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "/usr/local/lib/python3.7/site-packages/colorama/ansitowin32.py", line 174, in write_plain_text
    self.wrapped.write(text[start:end])
  File "/usr/local/lib/python3.7/site-packages/colorama/ansitowin32.py", line 40, in write
    self.__convertor.write(text)
  File "/usr/local/lib/python3.7/site-packages/colorama/ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "/usr/local/lib/python3.7/site-packages/colorama/ansitowin32.py", line 169, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "/usr/local/lib/python3.7/site-packages/colorama/ansitowin32.py", line 174, in write_plain_text
    self.wrapped.write(text[start:end])
  File "/usr/local/lib/python3.7/site-packages/_pytest/capture.py", line 358, in write
    self.buffer.write(obj)
ValueError: I/O operation on closed file
```
 
### Expected behaviour

I wouldn't expect the package to have any impact on these tests that isn't present when running the program.

## Steps to recreate
  * Run pytest unit tests on a program that uses halo as shown above

**Comment by manrajgrover** [comment] 2018-10-05 07:13
@tterb Thanks for reporting. I'll check if I can reproduce this issue on my end and get back to you on this.

**Comment by tterb** [comment] 2018-10-06 02:04
@manrajgrover Okay, let me know if more info is needed

**Comment by manrajgrover** [comment] 2018-10-17 08:43
@tterb I would need more information here. Could you please create a sample code to reproduce this issue? I tried doing it but couldn't.

**Comment by theY4Kman** [comment] 2018-10-20 21:07
Presuming halo runs some cleanup using an `atexit` func, this sounds more to me like halo writing to what it thinks is `sys.stdout`, but was really pytest's caplog — which presumably is a StringIO long-since closed by the time halo cleans up.

**Comment by theY4Kman** [comment] 2018-10-20 21:17
Here ya go: https://repl.it/repls/SorrowfulNaturalDisassembler

**Closed** 2019-05-29 09:48 UTC
Labels: bug, discussion
