### ISSUE TITLE
Bug: Cursor stays hidden after CTRL+C

### ISSUE THREAD

**Issue by ccc032** [ManrajGrover/halo#41] opened 2018-01-06 11:39 UTC
## Description
While a spinner is running, an unexpected exit of the script (like by pressing CTRL+C) makes the cursor stay hidden in the terminal.

### System settings

- Operating System: Void Linux
- Terminal in use: kitty
- Python version: 3.6.4
- Halo version: 0.0.9 (latest)
 
### Expected behaviour
The cursor should be made visible again.

## Steps to recreate
Cancel this script:
```
from halo import Halo
import time
spinner = Halo()
spinner.start(text="Press Ctrl-C now")
time.sleep(999)
```

## People to notify
@ManrajGrover

**Comment by ManrajGrover** [comment] 2018-01-10 16:22
@ccc032 I could not reproduce this error on my end. I'm thinking it is because of specific terminal usage. Could you confirm the same?

**Comment by ccc032** [comment] 2018-01-10 22:02
@ManrajGrover I get this bug no matter what terminal I try (kitty, xterm, urxvt, Linux tty). Is there any other information I can provide?

**Comment by ManrajGrover** [comment] 2018-01-11 06:58
@ccc032 Got it. Looks like this has already been fixed in HEAD but has not been released. Making a release to 0.0.10 with latest HEAD should fix this.

**Comment by ManrajGrover** [comment] 2018-01-11 07:18
@ccc032 Please try version `0.0.10` and let me know if the error still persists.

**Comment by ccc032** [comment] 2018-01-12 07:07
@ManrajGrover Latest version fixed it for me, thanks.

**Comment by ManrajGrover** [comment] 2018-01-12 07:19
@ccc032 Thanks for confirming. Closing this.

**Closed by ManrajGrover** 2018-01-12 07:19 UTC
Labels: bug, discussion
